version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
  
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: calavera
      MYSQL_DATABASE: SpotifusNueva
      MYSQL_USER: mai
      MYSQL_PASSWORD: calavera
    ports:
      - "3306:3306"
    volumes:
      - basedatos:/var/lib/mysql
      - ./realdatabase.sql:/docker-entrypoint-initdb.d/realdatabase.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: calavera
      MYSQL_USER: mai
      MYSQL_PASSWORD: calavera

volumes:
  basedatos:
